apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer
  name: msg-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer
    spec:
      containers:
      - image: homnik/baltikadev:0.0.3
        name: msg-processor
        ports:
        - containerPort: 8080
